spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/colheplus}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:colheplus}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:colheplus}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
