name: CD Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ColhePlus

            git pull origin main

            mvn clean package -DskipTests

            pkill -f 'java -jar' || true

            nohup java -jar target/*.jar > app.log 2>&1 &
